### PR TITLE
Feature/styling

### PR DESCRIPTION
**Pull request by cmarshall13**

### CODE REVIEW

**Review by RynMrphy18 — COMMENTED** [review]
Looks good, we made at least most of the match functionality last night so hopefully we can put that into develop soon

**Review by smurphy7326 — APPROVED** [review]
Dope Corrine, awesome

**Review by RynMrphy18 — APPROVED** [review]

**Review by JPDBrodeur — APPROVED** [review]
Styling for the win!

**Review by thereeling — APPROVED** [review]
Looks good!  Might have some merge conflicts with signup and profile but we'll sort it out

**Pull request merged**
