### PR TITLE
Feature/front end

### PR DESCRIPTION
**Pull request by thereeling**
## Merging Front end into develop
 For the front-end, we'll delete unused branches an get a pseudo reset for the GitHub Repo

### CODE REVIEW

**Review by RynMrphy18 — APPROVED** [review]

**Review by smurphy7326 — APPROVED** [review]
YUP, YES

**Review by JPDBrodeur — APPROVED** [review]
Looks good, Nick.

**Review by thereeling — COMMENTED** [review]
I looked it over!

**Review by cmarshall13 — APPROVED** [review]

**Comment by thereeling** [comment]
GOGOGOGOGOGOGO

**Pull request merged**
